### ISSUE TITLE
build settings have critical bugs

### ISSUE THREAD

**Issue by tktcorporation** [tkt-actions/add-issue-links#32]
# Overview
- build settings have critical bugs

# Bugs

- `tsc` and `ncc` create a built file in **dist/index.js**. but, launching the action, it has following critical error.

```
Run tkt-actions/add-issue-links@v1.0.4
  with:
    repo-token: ***
    branch-prefix: issue-
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'src/domain/Branch'
Require stack:
- /home/runner/work/_actions/tkt-actions/add-issue-links/v1.0.4/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.496 (/home/runner/work/_actions/tkt-actions/add-issue-links/v1.0.4/dist/index.js:1:76113)
    at __webpack_require__ (/home/runner/work/_actions/tkt-actions/add-issue-links/v1.0.4/dist/index.js:1:169)
    at Object.367 (/home/runner/work/_actions/tkt-actions/add-issue-links/v1.0.4/dist/index.js:1:38342)
    at __webpack_require__ (/home/runner/work/_actions/tkt-actions/add-issue-links/v1.0.4/dist/index.js:1:169)
    at Object.198 (/home/runner/work/_actions/tkt-actions/add-issue-links/v1.0.4/dist/index.js:1:20507)
    at __webpack_require__ (/home/runner/work/_actions/tkt-actions/add-issue-links/v1.0.4/dist/index.js:1:169) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/tkt-actions/add-issue-links/v1.0.4/dist/index.js'
  ]
}
```

## Error Messages

# Checks

- [x] Settings
- [x] Tests

**Comment by tktcorporation** [comment]
resolved in v1.0.5 release
